"""after regisration id1,2

Revision ID: 692ccafa0fb5
Revises: bf73dcad64b1
Create Date: 2021-06-10 15:21:30.730318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '692ccafa0fb5'
down_revision = 'bf73dcad64b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
